### ISSUE TITLE
editing reply

### ISSUE THREAD

**Issue by AmphoMoronal** [mautrix/whatsapp#433] opened 2022-02-01 18:08 UTC
If I edit an reply, I get something like that 
```
> !randomnumbers:domain.net @⁨name_of_person⁩
> answer * 
content
```
in WhattsApp.
And the chatting partner on WA see it also.

PS: My girlfriend was scared yesterday, when she get that

**Comment by tulir** [comment] 2022-02-01 18:12
Don't edit messages

(duplicate of #319)

**Closed by tulir** 2022-02-01 18:12 UTC
