### ISSUE TITLE
Whatsapp Bridge Docker failed to start due initializing matrix state store  mautrix-whatsapp 0.4.0

### ISSUE THREAD

**Issue by jpaechnatz** [mautrix/whatsapp#511] opened 2022-06-04 14:54 UTC
[Jun  4, 2022 14:48:17] [INFO] Initializing mautrix-whatsapp 0.4.0+dev.7f27c766 (May 31 2022, 14:29:49)
[Jun  4, 2022 14:48:17] [DEBUG] Initializing database connection
[Jun  4, 2022 14:48:17] [DEBUG] Initializing state store
[Jun  4, 2022 14:48:17] [DEBUG] Initializing Matrix event processor
[Jun  4, 2022 14:48:17] [DEBUG] Initializing Matrix event handler
[Jun  4, 2022 14:48:17] [INFO] Bridge initialization complete, starting...
[Jun  4, 2022 14:48:17] [DEBUG] Running database upgrades
[Jun  4, 2022 14:48:17] [Database/INFO] Database currently on v49, latest: v49
[Jun  4, 2022 14:48:17] [Database/StateStore/INFO] Database currently on v2, latest: v3
[Jun  4, 2022 14:48:17] [Database/StateStore/INFO] Upgrading database from v2 to v3: Disable nulls in mx_user_profile
[Jun  4, 2022 14:48:17] [FATAL] Failed to initialize matrix state store: near "ALTER": syntax error

Help with starting up my docker based bridge is very much appreciated, thanks ;-)

**Comment by tulir** [comment] 2022-06-04 15:42
That's an old version of the bridge

(also, duplicate of #509)

**Closed by tulir** 2022-06-04 15:42 UTC
Labels: bug
