### ISSUE TITLE
matrix -> whatsapp relies do not show replied-to message in whatsapp

### ISSUE THREAD

**Issue by JadedBlueEyes** [mautrix/whatsapp#754] opened 2024-12-17 15:40 UTC
When replying to a message from Matrix, the Whatsapp message doesn't contain the replied-to message, only a link to it. See:
![image](https://github.com/user-attachments/assets/589ee006-328c-4554-8a37-4dcddf47f2d7)
This is different from the behavior of official whatsapp clients

**Comment by tulir** [comment] 2024-12-17 15:46
Duplicate of #624

**Closed by tulir** 2024-12-17 15:46 UTC
Labels: bug
