### ISSUE TITLE
Replies not correctly bridged to Whatsapp

### ISSUE THREAD

**Issue by PATR1CK3076** [mautrix/whatsapp#711] opened 2024-08-21 18:57 UTC
When you reply to a text message in matrix the "replied to" text message in Whatsapp is blank instead of showing the actual text message.

![Screenshot_20240821-205438~2.png](https://github.com/user-attachments/assets/2616f75d-1051-4af5-b8a4-88b3b8e77089)

**Comment by tulir** [comment] 2024-08-21 19:02
Duplicate of #624

**Closed by tulir** 2024-08-21 19:02 UTC
Labels: bug
