### ISSUE TITLE
Possibility to don't puppet deletes

### ISSUE THREAD

**Issue by mxwmnn** [mautrix/whatsapp#550] opened 2022-09-05 20:38 UTC
It would be nice to configure that messages don't get deleted (puppeted) if the sender deletes it.

**Comment by maltee1** [comment] 2022-09-05 20:43
Nice for you but not for the sender. It's a bad idea if you ask me.

**Comment by mxwmnn** [comment] 2022-09-05 20:47
If I don't open Element I still see the messages in my push notifications. I'll read them first until I tap in and then they're gone. So I read anyways. Maybe the sender should take the time to know what he's writing/sending and I want every message which was sent to me.

**Comment by maltee1** [comment] 2022-09-05 20:58
Then that's a bug in element. There is no good reason to break intended behavior just because we can. Just like there is no option to leave people in groups after they've left on WhatsApp.

Also, if I'm not mistaken, this has been requested before, possibly for a different bridge, but was rejected for above reasons.

**Comment by mxwmnn** [comment] 2022-09-05 21:02
The Bridge also Stores WhatsApp Status Posts. This is also no intended behavior from WhatsApp cause after 24 hours it disappears... So this is not a real argument or is it a bug from mautrix WhatsApp too?

**Comment by maltee1** [comment] 2022-09-05 21:46
You're comparing apples to oranges (so was I, to be fair). Status broadcasts aren't deleted by the author, they just expire after a set amount of time. There probably isn't even a delete event from WhatsApp. And them being deleted isn't necessarily something that a matrix user should know about.
But most likely the reason is that status broadcasts aren't really a first class citizen and nobody has implemented their expiration yet.

**Comment by tulir** [comment] 2022-09-05 21:58
Duplicate of #237

**Comment by mxwmnn** [comment] 2022-09-05 21:59
Ah, okay. Sorry then I misunderstood the logic behind it. I'm interested in the answer from the devs.

**Closed by tulir** 2022-09-05 21:58 UTC
Labels: enhancement
