### ISSUE TITLE
Replies don't have text attached

### ISSUE THREAD

**Issue by JAicewizard** [mautrix/whatsapp#703] opened 2024-05-25 10:34 UTC
When replying to a message, the reply contains an "empty" message, and not the message being replied to.
See message below:
![empty-reply-to](https://github.com/mautrix/whatsapp/assets/19241481/0e10b376-6394-4b9d-af8d-0d5b5a8343c8)

I have the latest (or almost latest) version. I cannot verify but I updated recently and there haven't been any new released.

**Comment by tulir** [comment] 2024-05-25 10:38
Duplicate of #624

**Closed by tulir** 2024-05-25 10:38 UTC
Labels: bug
